### ISSUE TITLE
Install warp and use it in Linux

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-warp#16]
Seems warp is on linux...

https://github.com/warpem/warp/?tab=readme-ov-file#building-warp-on-linux

@azazellochg we can do it if you do not have time. Let us know.

**Comment by azazellochg** [comment]
If I remember correctly warp is used to do only preprocessing: motion correction, ctf estimation and picking. If it requires imod, aretomo and relion pre-installed, then what does it actually do itself? Sounds like just a wrapper for these programs? Happy to be wrong

**Comment by pconesa** [comment]
Then we can do just CTF estimation and MC?

**Comment by azazellochg** [comment]
here are the new programs: https://github.com/warpem/warp/blob/main/CHANGELOG#L11

**Comment by azazellochg** [comment]
@pconesa I've started working on this in warp2 branch
