### ISSUE TITLE
Extracting 3D coordinates in tomograms has a problem because of name change

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-warp#35]
Hello cool people

I've been removing this extra "_deconv" suffix from the output tomograms each time I need to extract 3D coordinates (from deconvoluted tomograms to raw). 
https://github.com/scipion-em/scipion-em-warp/blob/master/warp/protocols/protocol_base.py#L134

Why this is a thing?
Because we usually pick data on deconvolved or denoised tomograms, then we want to return to the original tomograms to do any processing.

I'm very excited to try the new functionalities of Warp in Scipion.

Cheers
Mohamad

**Comment by azazellochg** [comment]
Hi! Can you describe the workflow or attach the json? The coordinates extraction should be based on tsId, not on the filenames, but maybe we have a problem there.

**Comment by MohamadHarastani** [comment]
While trying to reproduce on the latest updates of everything I didn't face this issue :-)

Thanks for the continuous support Grigory! 
Mohamad
